<a href="https://colab.research.google.com/github/vkjadon/python/blob/main/eigenValuesVector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Eigen Values and Vectors

Eigenvalues are like the "natural" settings of a system, telling you the frequencies, energies, or other quantities that are intrinsic to the system. Whereas, the eigenvectors are like the "directions" or "shapes" that correspond to these natural settings, showing how the system behaves or vibrates.

A=[
4
1
​
  
−2
1
​
 ]
 ### Calculate the Eigenvalues
 , the eigenvalues are:

𝜆1=2, 𝜆2=3,

Eigenvalue 𝜆1=2 corresponds to eigenvector [1 1]
Eigenvalue 𝜆2=3 corresponds to eigenvector [2 1]



hysical Significance
Eigenvalues:

𝜆1 = 2 and 𝜆2 = 3 represent scaling factors along the directions defined by their respective eigenvectors.
In a physical system, these could represent natural frequencies in a vibrational system or growth/decay rates in a dynamic system.
If the eigenvalues increase: The system's response becomes faster or more intense. For example, in a mechanical system, higher eigenvalues could mean higher frequencies of vibration, leading to quicker oscillations.
If the eigenvalues decrease: The system's response slows down. Lower eigenvalues could correspond to lower frequencies or slower dynamics.
Eigenvectors:

The eigenvectors [1 1] and describe the directions in which these effects occur.
If the eigenvalues increase or decrease: The direction (eigenvector) itself doesn’t change, but the magnitude of the effect along that direction (as described by the eigenvalue) does.

Practical Example Interpretation:
Imagine a simple mechanical system where
𝐴
A represents the transformation matrix of forces or displacements:

Eigenvalue 2 with eigenvector
[
1
1
]
[
1
1
​
 ] could represent a mode where both components of the system move equally in the same direction but with a lower frequency (or slower response).
Eigenvalue 3 with eigenvector
[
2
1
]
[
2
1
​
 ] could represent a mode where one component moves twice as much as the other but with a higher frequency (or faster response).
Changes in these eigenvalues would directly affect the stability and dynamics of the system.

##Vibrating String

Vibrating String (e.g., Guitar String)
Physical Setup: Imagine a guitar string fixed at both ends. When you pluck the string, it vibrates.
Eigenvalues: The eigenvalues correspond to the square of the natural frequencies of the string’s vibration. These frequencies are the specific pitches that the string produces.
Eigenvectors: The eigenvectors represent the mode shapes or patterns of vibration. For a guitar string, the simplest mode shape is when the string moves up and down in a single arc (fundamental frequency). More complex shapes (higher modes) have the string forming more loops, but these shapes still correspond to specific pitches.

Vibrating String: Eigenvalues are the natural frequencies; eigenvectors are the mode shapes of the string.

Rotating Disc (Principal Axes)
Physical Setup: Consider a flat, thin disc that you spin. If you spin it about its center, it rotates smoothly. But if you try to spin it about an axis that isn't aligned with one of the disc's principal axes, it wobbles.
Eigenvalues: The eigenvalues are related to the moments of inertia about the principal axes of the disc. These describe how resistant the disc is to rotational motion about each axis.
Eigenvectors: The eigenvectors are the directions of the principal axes. They tell you the directions in which the disc can spin without wobbling.

Rotating Disc: Eigenvalues are the moments of inertia; eigenvectors are the principal axes of rotation.

Spring-Mass System
Physical Setup: Imagine a mass hanging from a spring. If you pull the mass down and let it go, it oscillates up and down.
Eigenvalues: The eigenvalue in this case corresponds to the square of the natural frequency of the mass-spring system. This frequency is how fast the mass oscillates.
Eigenvectors: For this simple system, the eigenvector is just the direction of motion—straight up and down. In more complex systems with multiple masses, the eigenvectors describe the relative motion of each mass.

Spring-Mass System: Eigenvalues are the natural frequencies; eigenvectors describe the relative motion of masses.

In [ ]:
import numpy as np

# Mass matrix M (assume unit masses)
M = np.array([[2, 0],
              [0, 1]])

# Stiffness matrix K (spring constants)
K = np.array([[5, -2],
              [-2, 3]])

# Solve the eigenvalue problem (K - ω^2*M) = 0
eigvals, eigvecs = np.linalg.eig(np.linalg.inv(M).dot(K))

# Natural frequencies (square roots of eigenvalues)
frequencies = np.sqrt(eigvals)

print("Natural Frequencies (rad/s):", frequencies)
print("Mode Shapes (Eigenvectors):\n", eigvecs)

Natural Frequencies (rad/s): [1.14623703 2.04600603]
Mode Shapes (Eigenvectors):
 [[-0.64456735  0.51010647]
 [-0.76454754 -0.86011126]]


Room Acoustics
Physical Setup: Consider a room where sound is bouncing off the walls. Certain frequencies of sound will resonate in the room, creating standing waves.
Eigenvalues: These are the resonant frequencies at which the room naturally amplifies sound. They correspond to the frequencies at which the standing waves form.
Eigenvectors: The eigenvectors describe the shape of these standing waves—how the air molecules in the room move at each resonant frequency. For example, some parts of the room might have a lot of movement (antinodes), while others have none (nodes).


Room Acoustics: Eigenvalues are the resonant frequencies; eigenvectors describe the standing wave patterns.

Pendulum
Physical Setup: Think of a simple pendulum—a weight on a string. If you pull it to the side and release it, it swings back and forth.
Eigenvalues: The eigenvalue corresponds to the square of the natural frequency of the pendulum's oscillation, which depends on the length of the string and gravity.
Eigenvectors: In this simple case, the eigenvector is just the direction of the pendulum's motion—back and forth along the arc.


Pendulum: Eigenvalue is the natural frequency; eigenvector is the direction of oscillation.

Power Systems Stability Analysis
In electrical engineering, eigenvalues and eigenvectors are used to assess the stability of power systems. The eigenvalues of the system's Jacobian matrix indicate how the system responds to disturbances.

Example:
Consider a simple two-bus power system where the eigenvalues of the Jacobian matrix are analyzed to determine stability.

In [ ]:
import numpy as np

# Jacobian matrix J for a power system
J = np.array([[0.4, -0.2],
              [-0.2, 0.3]])

# Calculate eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(J)

print("Eigenvalues (Stability Indicators):", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues (Stability Indicators): [0.55615528 0.14384472]
Eigenvectors:
 [[ 0.78820544  0.61541221]
 [-0.61541221  0.78820544]]


Principal Component Analysis (PCA) in Data Compression
In signal processing and data analysis, PCA is used to reduce the dimensionality of data. The eigenvectors of the covariance matrix represent the directions of maximum variance, and the eigenvalues indicate the amount of variance in each direction.

Example:
Consider a dataset where PCA is applied to find the principal components.

In [ ]:
import numpy as np

# Sample 2D dataset
data = np.array([[2.5, 2.4],
                 [0.5, 0.7],
                 [2.2, 2.9],
                 [1.9, 2.2],
                 [3.1, 3.0],
                 [2.3, 2.7],
                 [2.0, 1.6],
                 [1.0, 1.1],
                 [1.5, 1.6],
                 [1.1, 0.9]])

# Subtract the mean
mean = np.mean(data, axis=0)
data_centered = data - mean

# Calculate the covariance matrix
cov_matrix = np.cov(data_centered, rowvar=False)

# Find the eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(cov_matrix)

# Principal components (eigenvectors)
print("Principal Components:\n", eigvecs)

# Variance explained (eigenvalues)
print("Variance Explained (Eigenvalues):", eigvals)


Structural Engineering: Buckling Analysis
In structural engineering, eigenvalue analysis is used to determine the buckling load of columns. The critical load at which a structure will buckle corresponds to the eigenvalue of the system.

Example:
Consider a column under compression. The eigenvalue problem helps determine the critical buckling load.

In [ ]:
import numpy as np

# Assume a simplified column with stiffness matrix K and load P
K = np.array([[12, -6],
              [-6, 4]])

# The buckling load factor P (scaling factor)
P = np.array([[1, 0],
              [0, 0.5]])

# Solve the eigenvalue problem (K - P*λ) = 0
eigvals, eigvecs = np.linalg.eig(np.linalg.inv(P).dot(K))

# Critical buckling loads (eigenvalues)
print("Critical Buckling Loads:", eigvals)
print("Buckling Mode Shapes (Eigenvectors):\n", eigvecs)


Critical Buckling Loads: [18.71779789  1.28220211]
Buckling Mode Shapes (Eigenvectors):
 [[ 0.66613722  0.48848147]
 [-0.7458292   0.87257427]]


Control Systems: Stability of Dynamic Systems
In control engineering, eigenvalues of the system's state matrix determine the stability of dynamic systems. If all eigenvalues have negative real parts, the system is stable.

Example:
Consider a state-space representation of a control system where the state matrix is analyzed for stability.

In [ ]:
import numpy as np

# State matrix A for a control system
A = np.array([[0, 1],
              [-2, -3]])

# Calculate eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues (Stability Analysis):", eigvals)
print("Eigenvectors (Modes of System):\n", eigvecs)

# Check if the system is stable
is_stable = np.all(np.real(eigvals) < 0)
print("Is the system stable?", is_stable)


Eigenvalues (Stability Analysis): [-1. -2.]
Eigenvectors (Modes of System):
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]
Is the system stable? True


Modal Analysis in Aerospace Engineering
In aerospace engineering, modal analysis uses eigenvalues and eigenvectors to study the dynamic behavior of aircraft structures under different loading conditions.

Example:
Consider an aircraft wing modeled as a beam. The natural frequencies (eigenvalues) and mode shapes (eigenvectors) can be analyzed.

In [ ]:
import numpy as np

# Simplified stiffness matrix for a wing model
K = np.array([[3, -1, 0],
              [-1, 4, -1],
              [0, -1, 2]])

# Mass matrix (assuming unit masses)
M = np.identity(3)

# Solve the eigenvalue problem for dynamic analysis
eigvals, eigvecs = np.linalg.eig(np.linalg.inv(M).dot(K))

# Natural frequencies (eigenvalues)
frequencies = np.sqrt(eigvals)

print("Natural Frequencies (Hz):", frequencies)
print("Mode Shapes (Eigenvectors):\n", eigvecs)


Natural Frequencies (Hz): [2.20893306 1.62871227 1.21157382]
Mode Shapes (Eigenvectors):
 [[-0.44909879 -0.84402963  0.29312841]
 [ 0.84402963 -0.29312841  0.44909879]
 [-0.29312841  0.44909879  0.84402963]]


##Transformation

Rotate a point (x, y) around the origin by a given angle 𝜃.

In [1]:
import numpy as np

# Define the rotation matrix for a given angle theta
theta = np.radians(45)  # converting degrees to radians
rotation_matrix = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# Define the point to be rotated
point = np.array([1, 0])

# Perform the rotation
rotated_point = np.dot(rotation_matrix, point)

print("Original point:", point)
print("Rotated point by 45 degrees:", rotated_point)


Original point: [1 0]
Rotated point by 45 degrees: [0.70710678 0.70710678]
