In [ ]:
import numpy as np

In [ ]:
a = np.array([[0, 1], [1, 0]])
eigenValues, eigenVector=np.linalg.eig(a)
print('Eigen Values = ',eigenValues)
print('Eigen Vector = ',np.round(eigenVector,2))

Eigen Values =  [ 1. -1.]
Eigen Vector =  [[ 0.71 -0.71]
 [ 0.71  0.71]]


In [ ]:
A = np.matrix([[1,2,7],[2,8,3],[7,8,1]])
rank=np.linalg.matrix_rank(A)
print('Rank of Matrix = ',rank)

Rank of Matrix =  3


In [ ]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

print('Vertical Append:', np.vstack((f, g)))

a = np.array([[1,1,2], [2,2,3], [4,3,3]])
b = np.array([[5,1,2], [6,2,3], [7,3,4]])
stack=np.vstack((a,b))
print('Vertical Stack', stack)
print(stack[5][0])

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
Vertical Stack [[1 1 2]
 [2 2 3]
 [4 3 3]
 [5 1 2]
 [6 2 3]
 [7 3 4]]
7


Consider random arrays of shape `a(4,3)` and `b(3,2)`. 
`np.dot(a, b)` has shape equal to number of rows of `a`, number of columns of `b` 

- In numpy the `*` operator indicates element-wise multiplication and is different from `np.dot`. 

- Dot Product is also known as inner product

In [ ]:
a=np.random.randn(4,3)
#a=np.random.randn(3,2)
b=np.random.randn(3,2)
c=a*b
print(c)

ValueError: ignored

<span style="color:blue;">To perform element-wise multiplication, the dimension of both the arrays must be the same.</span>

<span style="color:brown">The other method is broadcating.</span>


In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,22).reshape(4,3)
c=a*b
print(c)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]
 [171 200 231]]


In [ ]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
c=np.dot(a,b)
c.shape

The columns and rows condition not satisfied


To perform `dot product` on two muti-dimension arrays, the last dimension of the first array should be equal to last but one dimension of second array. So check `a.shape[-1]==b.shape[-2]`

In [ ]:
print(a.shape[-1], b.shape[-2])
a.shape[-1] == b.shape[-2]

15 15


True

In [ ]:
a=np.random.randn(256,16)
b=np.random.randn(15,5)
if(a.shape[1] == b.shape[0]):
  c=np.dot(a,b)
  c.shape
  print(c)
else:
  print("The columns and rows condition not satisfied")

In [ ]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
c=a+b.T
print("Shape of a+b.T ",c.shape)
c=a.T+b
print("Shape of a.T+b ",c.shape)

Shape of a+b.T  (3, 4)
Shape of a.T+b  (4, 3)


In [ ]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

[[-1.5580882   1.05733325 -0.33846978]
 [-1.49086263  1.33664475 -1.25737294]
 [ 0.44572928 -0.26445954  0.48027482]]


if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [ ]:
print(a)
b=a+3
print(b)
b=b*7
print(b)

[[-1.039132    0.70516471 -0.22573484]
 [ 1.67919837 -1.50549865  1.41621269]
 [ 1.12516319 -0.66758042  1.21236717]]
[[1.960868   3.70516471 2.77426516]
 [4.67919837 1.49450135 4.41621269]
 [4.12516319 2.33241958 4.21236717]]
[[13.726076   25.93615297 19.41985615]
 [32.75438857 10.46150946 30.91348886]
 [28.87614235 16.32693708 29.48657021]]


Create an array corresponding to `(px_x*px_y*3)` and reshape to `(px_x, px_y,3)` and use `image.shape[0]`, `image.shape[1]` and `image.shape[2]`  

We can also use `image.reshape(-1,1)` for arranging all elements in a column vector. `-1` represnt unknown rows.  

We can also use `(1,-1)` for unknown columns and one row if required. 

In [ ]:
a=np.random.randn(4*4*3)
image=a.reshape(4,4,3)
image.shape[0]
image.reshape(-1,1)

In [ ]:
image.reshape(1,-1)

In [ ]:
a=np.array([[1,4, 5],[3,5,8]])  
b=np.sum(a,axis=1)  # 0 is column and 1 is row
b  

In [ ]:
import time

x1 = np.arange(10000)
x2 = np.arange(10000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot using for loop Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot without loop Computation time = " + str(1000 * (toc - tic)) + "ms")
print(dot)


dot using for loop Computation time = 10.708328999996297ms
dot without loop Computation time = 0.13821499999266962ms
333283335000


In [ ]:
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer =  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
#print(outer)

In [ ]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication  ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication ----- Computation time = " + str(1000*(toc - tic)) + "ms")


elementwise multiplication  ----- Computation time = 7.84616699999674ms
elementwise multiplication ----- Computation time = 0.914234000020997ms


In [ ]:
### CLASSIC DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
#print(W)
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")
### VECTORIZED DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("dot ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

gdot ----- Computation time = 27.605869000012717ms
dot ----- Computation time = 1.2613229999942632ms
